
from pathlib import Path
import subprocess as sp
import re


def read_fasta(fasta_file):
	sequences = dict()
	with fasta_file.open('r') as fasta_in:
		line = fasta_in.readline()
		while line:
			if line.startswith(f">"):
				line = line.rstrip('\r\n').split(maxsplit=1)
				header = line[0]
				seq = list()
				line = fasta_in.readline()
				while line and not line.startswith('>'):
					seq += line.rstrip('\r\n')
					line = fasta_in.readline()
				sequences[header] = ''.join(seq)
			else:
				line = fasta_in.readline()
	return sequences


def check_fastas_with_cerberus(fasta_folder:Path, cerberus_db:Path, output_folder:Path, hmm_list="KOFam_all", cpus:int=4):
	"""
	Check FASTA files against the Cerberus database.

	Parameters:
	fasta_folder (Path): Path to the folder containing FASTA files.
	cerberus_db (Path): Path to the Cerberus database file.
	output_folder (Path): Path to the folder where results will be saved.
	"""
	output_folder.mkdir(parents=True, exist_ok=True)

	log = output_folder / f"stdout.log"
	with open(log, 'w') as out_f, log.with_name("stderr.log").open('w') as err_f:
		# Run Cerberus
		cmd = ["cerberus.py", "--protein", str(fasta_folder), "--hmm", hmm_list, "--db", str(cerberus_db), "--dir-out", str(output_folder), "--cpus", str(cpus)]
		result = sp.run(cmd, stderr=err_f, stdout=out_f)

	# Process Cerberus output files
	process_cerberus_output(fasta_folder, output_folder)
	return output_folder


def process_cerberus_output(fasta_folder:Path, output_folder:Path):
	"""
	Process the output files generated by Cerberus.
	Parameters:
	fasta_folder (Path): Path to the folder containing original FASTA files.
	output_folder (Path): Path to the folder where Cerberus results are saved.
	"""
	out_passed = output_folder / "cerberus_passed"
	out_failed = output_folder / "cerberus_failed"
	out_passed.mkdir(parents=True, exist_ok=True)
	out_failed.mkdir(parents=True, exist_ok=True)

	re_fasta_name = re.compile(r'annotations-Protein_(.+)/final_annotation_summary.tsv')
	for tsv_file in output_folder.glob("final/annotations-*/final_annotation_summary.tsv"):
		fasta_name = re_fasta_name.search(str(tsv_file)).group(1)
		gene_name = fasta_name.split('_')[0]
		print(f"Processing Cerberus results for gene: {gene_name}")
		sequences = dict()
		with tsv_file.open() as reader:
			reader.readline()  # Skip header
			for line in reader:
				line = line.rstrip('\r\n').split('\t')
				target = line[0]
				product = line[1]
				best_hit = line[2]
				HMM = line[3]
				evalue = line[4]
				score = line[5]
				EC = line[6]
				gene = line[7]
				#ORF_start = line[8]
				#ORF_end = line[9]
				#ORF_length-aa = line[10]
				#product_start = line[11]
				#product_end = line[12]
				#product_length = line[13]

				match1 = re.search(gene_name, product)
				match2 = re.search(gene_name, gene)
				if match1 or match2:
					output_fasta = out_passed / f"{fasta_name}.faa"
					with output_fasta.open('a') as fasta_out:
						fasta_out.write(f">{target} {product} {gene} | Cerberus_HMM:{HMM} Best_Hit:{best_hit} | Evalue:{evalue} | Score:{score} | EC:{EC}\n")
						if not sequences:
							sequences = read_fasta(fasta_folder / f"{fasta_name}.faa")	
						fasta_seq = sequences.get(f">{target}")
						if fasta_seq:
							for s in range(0, len(fasta_seq), 80):
								fasta_out.write(f"{fasta_seq[s:s+80]}\n")
						else:
							print(f"Warning: Sequence {target} not found in original FASTA.")
				else:
					output_fasta = out_failed / f"{fasta_name}.faa"
					with output_fasta.open('a') as fasta_out:
						fasta_out.write(f">{target} {product} {gene} | Cerberus_HMM:{HMM} Best_Hit:{best_hit} | Evalue:{evalue} | Score:{score} | EC:{EC}\n")
						if not sequences:
							sequences = read_fasta(fasta_folder / f"{fasta_name}.faa")	
						fasta_seq = sequences.get(f">{target}")
						if fasta_seq:
							for s in range(0, len(fasta_seq), 80):
								fasta_out.write(f"{fasta_seq[s:s+80]}\n")
						else:
							print(f"Warning: Sequence {target} not found in original FASTA.")

	return out_passed
